#!/usr/bin/env bash

REL=$(dirname $0)

for BIN in $(ls $REL/bin) ; do

  echo -e "=== $BIN ===\n"

  if [[ $1 = timed ]] ; then
    time $REL/bin/$BIN $2
  else
    $REL/bin/$BIN $1
  fi

  echo

done

